import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Doctor",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  keywords: "Car Doctor, Car, Doctor, Service",
  authors: [{ name: "Car Doctor" }],
  creator: "Car Doctor",
  publisher: "Car Doctor",
  openGraph: {
    title: "Car Doctor",
    description: "Car Doctor - Your trusted car service partner",
    url: "https://cardoctor.com",
    siteName: "Car Doctor",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Car Doctor - Your trusted car service partner",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Car Doctor",
    description: "Car Doctor - Your trusted car service partner",
    images: "/og-image.png",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: "no",
  },
  robots: {
    index: true,
    follow: true,
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
